export const novaPoolHookAbi = [
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolManager",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isConfigured",
    inputs: [{ name: "", type: "bytes32", internalType: "PoolId" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCurrentFee",
    inputs: [{ name: "pid", type: "bytes32", internalType: "PoolId" }],
    outputs: [{ name: "", type: "uint24" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMaturityInfo",
    inputs: [{ name: "pid", type: "bytes32", internalType: "PoolId" }],
    outputs: [
      { name: "phase", type: "uint8" },
      { name: "cumulativeVolume", type: "uint256" },
      { name: "uniqueTraders", type: "uint32" },
      { name: "age", type: "uint256" },
      { name: "currentFee", type: "uint24" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolConfigs",
    inputs: [{ name: "", type: "bytes32", internalType: "PoolId" }],
    outputs: [
      { name: "baseFee", type: "uint24" },
      { name: "matureFee", type: "uint24" },
      { name: "maxSwapPctBps", type: "uint16" },
      { name: "largeTradeCooldown", type: "uint32" },
      { name: "largeTradePctBps", type: "uint16" },
      { name: "volumeForEmerging", type: "uint256" },
      { name: "volumeForGrowing", type: "uint256" },
      { name: "volumeForEstablished", type: "uint256" },
      { name: "minTradersEmerging", type: "uint32" },
      { name: "minTradersGrowing", type: "uint32" },
      { name: "minTradersEstablished", type: "uint32" },
      { name: "minAgeEmerging", type: "uint32" },
      { name: "minAgeGrowing", type: "uint32" },
      { name: "minAgeEstablished", type: "uint32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolMetrics",
    inputs: [{ name: "", type: "bytes32", internalType: "PoolId" }],
    outputs: [
      { name: "phase", type: "uint8" },
      { name: "cumulativeVolume", type: "uint256" },
      { name: "uniqueTraders", type: "uint32" },
      { name: "createdAt", type: "uint256" },
      { name: "lastSwapAt", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCooldownExpiry",
    inputs: [
      { name: "pid", type: "bytes32", internalType: "PoolId" },
      { name: "trader", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasTraded",
    inputs: [
      { name: "", type: "bytes32", internalType: "PoolId" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "configurePool",
    inputs: [
      {
        name: "key",
        type: "tuple",
        components: [
          { name: "currency0", type: "address" },
          { name: "currency1", type: "address" },
          { name: "fee", type: "uint24" },
          { name: "tickSpacing", type: "int24" },
          { name: "hooks", type: "address" },
        ],
      },
      {
        name: "config",
        type: "tuple",
        components: [
          { name: "baseFee", type: "uint24" },
          { name: "matureFee", type: "uint24" },
          { name: "maxSwapPctBps", type: "uint16" },
          { name: "largeTradeCooldown", type: "uint32" },
          { name: "largeTradePctBps", type: "uint16" },
          { name: "volumeForEmerging", type: "uint256" },
          { name: "volumeForGrowing", type: "uint256" },
          { name: "volumeForEstablished", type: "uint256" },
          { name: "minTradersEmerging", type: "uint32" },
          { name: "minTradersGrowing", type: "uint32" },
          { name: "minTradersEstablished", type: "uint32" },
          { name: "minAgeEmerging", type: "uint32" },
          { name: "minAgeGrowing", type: "uint32" },
          { name: "minAgeEstablished", type: "uint32" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "PhaseAdvanced",
    inputs: [
      { name: "poolId", type: "bytes32", indexed: false },
      { name: "from", type: "uint8", indexed: false },
      { name: "to", type: "uint8", indexed: false },
      { name: "cumulativeVolume", type: "uint256", indexed: false },
      { name: "uniqueTraders", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "GraduatedFeeApplied",
    inputs: [
      { name: "poolId", type: "bytes32", indexed: false },
      { name: "phase", type: "uint8", indexed: false },
      { name: "fee", type: "uint24", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CooldownApplied",
    inputs: [
      { name: "poolId", type: "bytes32", indexed: false },
      { name: "trader", type: "address", indexed: false },
      { name: "expiresAt", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PoolConfigured",
    inputs: [
      { name: "poolId", type: "bytes32", indexed: false },
      {
        name: "config",
        type: "tuple",
        indexed: false,
        components: [
          { name: "baseFee", type: "uint24" },
          { name: "matureFee", type: "uint24" },
          { name: "maxSwapPctBps", type: "uint16" },
          { name: "largeTradeCooldown", type: "uint32" },
          { name: "largeTradePctBps", type: "uint16" },
          { name: "volumeForEmerging", type: "uint256" },
          { name: "volumeForGrowing", type: "uint256" },
          { name: "volumeForEstablished", type: "uint256" },
          { name: "minTradersEmerging", type: "uint32" },
          { name: "minTradersGrowing", type: "uint32" },
          { name: "minTradersEstablished", type: "uint32" },
          { name: "minAgeEmerging", type: "uint32" },
          { name: "minAgeGrowing", type: "uint32" },
          { name: "minAgeEstablished", type: "uint32" },
        ],
      },
    ],
  },
] as const;
